-- Login, password-reset, and user create/update now normalize email
-- addresses (trim + lowercase) before storing or looking them up, so
-- "Test.Test@test.de" and "test.test@test.de" are treated as the same
-- account. This backfills any account created before that change so
-- existing users aren't locked out by a login attempt that no longer
-- matches the exact case stored in the database.
--
-- Note: if two accounts already differ only by case (e.g. "A@x.com" and
-- "a@x.com"), this UPDATE fails on the `email` unique constraint — such
-- duplicates need to be resolved manually before this migration can apply.
UPDATE "User" SET "email" = LOWER("email");
